//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeriousGame.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JEU()
        {
            this.EQUIPEs = new HashSet<EQUIPE>();
        }
    
        public int ID { get; set; }
        public Nullable<int> NB_ETAPE { get; set; }
        public string CODE { get; set; }
        public Nullable<bool> ENCOURS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPE> EQUIPEs { get; set; }
    }
}
