//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeriousGame.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUIZZ
    {
        public int ID { get; set; }
        public string QUESTION { get; set; }
        public string REPONSE1 { get; set; }
        public string REPONSE2 { get; set; }
        public string REPONSE3 { get; set; }
        public string REPONSE4 { get; set; }
        public string BONNEREPONSE { get; set; }
    }
}
