//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeriousGame.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class teamtimEntities : DbContext
    {
        public teamtimEntities()
            : base("name=teamtimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLASSEMENT> CLASSEMENTs { get; set; }
        public virtual DbSet<EQUIPE> EQUIPEs { get; set; }
        public virtual DbSet<ETAPE> ETAPEs { get; set; }
        public virtual DbSet<JEU> JEUs { get; set; }
        public virtual DbSet<JOUEUR> JOUEURs { get; set; }
        public virtual DbSet<STATISTIQUE> STATISTIQUEs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
